### ISSUE TITLE
[jacobsen on 2007-12-05 19:05:16] : pDAQ: SecondaryBuilders - splicedAnalysis crashes at end of run

### ISSUE THREAD

**Issue by dglo** [dglo/secondaryBuilders#21]
Faulty/dangerous comparison

secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer WARN [2007-12-05 18:50:52.127] Splicer contains: [-5:0]
secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer WARN [2007-12-05 18:50:52.127] index 5 start 5 decrement 0 num 0
secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer WARN [2007-12-05 18:50:52.126] index 4 start 2 decrement 1 num 5
secondaryBuilders icecube.daq.splicer.HKN1Splicer-HKN1Splicer ERROR [2007-12-05 18:50:52.127] EMPTY LIST!!!
secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer WARN [2007-12-05 18:50:52.127] Splicer contains: [-5:0]
secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer WARN [2007-12-05 18:50:52.127] index 5 start 5 decrement 0 num 0
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.131] Exception in thread "HKN1Splicer" Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.131] java.lang.IndexOutOfBoundsException: Index: 5, Size: 0
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.131] Exception in thread "HKN1Splicer" java.lang.IndexOutOfBoundsException: Index: 2, Size: 0
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.RangeCheck(ArrayList.java:572)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.RangeCheck(ArrayList.java:572)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.RangeCheck(ArrayList.java:572)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.get(ArrayList.java:347)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.get(ArrayList.java:347)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at java.util.ArrayList.get(ArrayList.java:347)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at icecube.daq.secBuilder.SBSplicedAnalysis.execute(SBSplicedAnalysis.java:76)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at icecube.daq.secBuilder.SBSplicedAnalysis.execute(SBSplicedAnalysis.java:76)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:351)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.132]    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:351)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.133]    at java.lang.Thread.run(Thread.java:801)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.133]    at java.lang.Thread.run(Thread.java:801)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.133]    at icecube.daq.secBuilder.SBSplicedAnalysis.execute(SBSplicedAnalysis.java:76)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.133]    at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:351)
secondaryBuilders STDERR-HKN1Splicer ERROR [2007-12-05 18:50:52.133]    at java.lang.Thread.run(Thread.java:801)

**Comment by dglo** [comment]
[jacobsen on 2007-12-05 20:06:21]
Sending        secondaryBuilders/src/main/java/icecube/daq/secBuilder/SBSplicedAnalysis.java
Transmitting file data .
Committed revision 2381.
