### ISSUE TITLE
[tbendfelt on 2015-10-09 02:32:41] : pDAQ: SecondaryBuilder - String format error while logging error message

### ISSUE THREAD

**Issue by dglo** [dglo/secondaryBuilders#67]
(From Run 126958)

Type mismatch while formatting an error message.

secondaryBuilders icecube.daq.secBuilder.SBSplicedAnalysis-HKN1Splicer+icecube.daq.secBuilder.MoniAnalysis@7b64769 ERROR [2015-10-08 23:04:22.5600000000] Unexpected monitoring error from HardwareMonitor[time 242750231002145197 dom 9684326e9778 clk 30678742627 evtVersion 1 adcVoltSum 14 adc5VPower 1007 adcPressure 265 adc5VCurrent 464 adc33VCurrent 82 adc25VCurrent 41 adc18VCurrent 101 adcMinus5VCurrent 136 dacATWD0TrigBias 799 dacATWD0RampTop 2300 dacATWD0RampRate 350 dacATWDAnalogRef 2250 dacATWD1TrigBias 805 dacATWD1RampTop 2300 dacATWD1RampRate 350 dacPMTFEPed 2130 dacMultiSPEThresh 661 dacSingleSPEThresh 561 dacLEDBright 1023 dacFastADCRef 800 dacIntPulser 0 dacFEAmpLowClamp 0 dacFLRef 450 dacMuxBias 500 pmtBaseHVSetVal 2590 pmtBaseHVMonVal 2590 domTemp -6544 spe 379 mpe 3]
java.util.IllegalFormatConversionException: x != java.lang.String
	at java.util.Formatter$FormatSpecifier.failConversion(Formatter.java:4045)
	at java.util.Formatter$FormatSpecifier.printInteger(Formatter.java:2748)
	at java.util.Formatter$FormatSpecifier.print(Formatter.java:2702)
	at java.util.Formatter.format(Formatter.java:2488)
	at java.util.Formatter.format(Formatter.java:2423)
	at java.lang.String.format(String.java:2790)
	at icecube.daq.secBuilder.MoniAnalysis.gatherMonitoring(MoniAnalysis.java:277)
	at icecube.daq.secBuilder.SBSplicedAnalysis.analyze(SBSplicedAnalysis.java:79)
	at icecube.daq.splicer.HKN1Splicer.run(HKN1Splicer.java:359)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dglo** [comment]
[dglo on 2015-10-12 16:50:27]
svn commit -m"Issue 7582: Fix error message format and only report it once"
Sending        src/main/java/icecube/daq/secBuilder/MoniAnalysis.java
Transmitting file data .done
Committing transaction...
Committed revision 15806.

**Comment by dglo** [comment]
[dglo on 2016-03-22 16:06:03]
New_Glarus is almost here!
